name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: the name of the deployable artifact file
        required: true
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."